spring:
  application:
    name: Moneymate



  datasource:
    url: jdbc:mysql://localhost:3307/moneymate_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: moneymate_user
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  #    defer-datasource-initialization: true

  sql:
    init:
      mode: never


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8080

market:
  asset-master:
    enabled: true
    kospi-zip-path: C:/Users/minta/Downloads/kospi_code.mst.zip
    kosdaq-zip-path: C:/Users/minta/Downloads/kosdaq_code.mst.zip


