spring:
  application:
    name: Moneymate



  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/moneymate_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:moneymate_user}
    password: ${SPRING_DATASOURCE_PASSWORD:qwer1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  #    defer-datasource-initialization: true

  sql:
    init:
      mode: never


springdoc:
  paths-to-match: /**
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

server:
  port: 8080

market:
  asset-master:
    enabled: true
    csv-path: classpath:/data/kr_assets.csv


